// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq-Uc05J0dqK-iMQsu_9cBEAYGjYwaIu4',
    appId: '1:62395291752:web:04c7de01e40007f1c343dd',
    messagingSenderId: '62395291752',
    projectId: 'flicker-60df8',
    authDomain: 'flicker-60df8.firebaseapp.com',
    storageBucket: 'flicker-60df8.appspot.com',
    measurementId: 'G-8X12LZH55P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXCDieUvPSqbpGlavFgKj9quAS_Jo62R4',
    appId: '1:62395291752:android:7893da3baafa82c7c343dd',
    messagingSenderId: '62395291752',
    projectId: 'flicker-60df8',
    storageBucket: 'flicker-60df8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHvd4CJFLiYlStyFrzmV7Ivj-2YciUpPs',
    appId: '1:62395291752:ios:e727b39de997f2b7c343dd',
    messagingSenderId: '62395291752',
    projectId: 'flicker-60df8',
    storageBucket: 'flicker-60df8.appspot.com',
    iosClientId: '62395291752-8s8b6uqa55afk02bmakvpchvs7cu9j2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.lumos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHvd4CJFLiYlStyFrzmV7Ivj-2YciUpPs',
    appId: '1:62395291752:ios:e727b39de997f2b7c343dd',
    messagingSenderId: '62395291752',
    projectId: 'flicker-60df8',
    storageBucket: 'flicker-60df8.appspot.com',
    iosClientId: '62395291752-8s8b6uqa55afk02bmakvpchvs7cu9j2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.lumos',
  );
}
